services:
  iceberg-rest:
    image: apache/iceberg-rest-fixture
    container_name: iceberg-rest
    networks:
      iceberg_net:
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-rustfsadmin}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-rustfsadmin}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - CATALOG_WAREHOUSE=${CATALOG_WAREHOUSE:-s3://pb-bucket/}
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=${CATALOG_S3_ENDPOINT:-http://host.docker.internal:9000}
      - CATALOG_S3_PATH__STYLE__ACCESS=${CATALOG_S3_PATH_STYLE_ACCESS:-true}
networks:
  iceberg_net:
